{% set version = "3.4.0.3" %}

package:
  name: magics
  version: {{ version }}

source:
  fn: Magics-{{ version }}-Source.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/121845745/Magics-{{ version }}-Source.tar.gz
  sha256: 1fed6c087b59227d0e865e7b4c2a343b9528be88a423487d6d9eba3668efd788

build:
  number: 1000
  skip: True  # [win and vc<14]
  detect_binary_files_with_prefix: true
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-bash  # [win]
    - m2-findutils  # [win]
    - m2-coreutils  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
    - m2-gawk  # [win]
    - m2-diffutils  # [win]
    - m2-unzip  # [win]
  host:
    - pkgconfig  # [not win]
    - boost
    - expat
    - glib  # [not win]
    - pango  # [not win]
    - proj4
    - eccodes
    - perl  # [not win]
    - perl-xml-parser  # [not win]
    - m2-perl  # [win]
    - libnetcdf
    - pthreads-win32  # [win]
    - libiconv  # [win]
  run:
    - expat
    - pango  # [not win]
    - proj4
    - eccodes
    - simplejson  # [not win]
    - libnetcdf
    - pthreads-win32  # [win]
    - libiconv  # [win]

test:
  commands:
    - conda inspect linkages -p $PREFIX magics  # [not win]
    - conda inspect objects -p $PREFIX magics  # [osx]
  imports:
    - Magics
    - Magics.macro
    - Magics.metgram
    - Magics.toolbox

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF's Meteorological plotting software

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
