{% set version = "3.4.0.2" %}

package:
  name: magics
  version: {{ version }}

source:
  fn: Magics-{{ version }}-Source.tar.gz
  url: https://software.ecmwf.int/wiki/download/attachments/121845745/Magics-{{ version }}-Source.tar.gz
  sha256: 6e41247769891d9c5a2d155b1d0f50c7629f664d35c98d8fa1310f4fde2561e0

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - swig
    - pkgconfig
    - boost 1.64.*
    - expat 2.2.*
    - glib
    - pango 1.40.*
    - proj4 4.9.3
    - eccodes
    - perl 5.22.2.1
    - perl-xml-parser
    - netcdf4
  run:
    - expat 2.2.*
    - pango 1.40.*
    - proj4 4.9.3
    - eccodes
    - simplejson
    - netcdf4

test:
  commands:
    - conda inspect linkages -p $PREFIX magics  # [not win]
    - conda inspect objects -p $PREFIX magics  # [osx]
  imports:
    - Magics
    - Magics.macro
    - Magics.metgram
    - Magics.toolbox

about:
  home: https://software.ecmwf.int/wiki/display/MAGP/
  license: Apache 2.0
  license_family: Apache
  summary: ECMWF's Meteorological plotting software

extra:
  recipe-maintainers:
    - kynan
    - carletes
    - StephanSiemen
