travis:
  secure:
    BINSTAR_TOKEN: mylQqQ9JR50wzXcmhPKPRIxzYu99/PXiyNmGxSBj3HNW632FxlyhP6Sm/ip9E3ZtE7dQAANZq9CzbToXsO5PdcWZQV2S2sW3IvnyqH/iaxI9Spr6VkRdORVbgASLVbtqMkeFKuGIE92MXD+QSHhxOEdqrPgEjSL9EDbIA1NMtFd5b063/nXY01HojX53hRSl9FS/duKszh31r+F/3v/Bwfea7sMWBCgW2P2j0s9lXXg3MZX44ZqpaBs9AvI1HA4xYBmNqdL/P3PomHtL8/49wd2INDsTjjl5rTqyhu42XDSP3lt/Jo+3ijlChBxTXn5SE/gPkAFFxpBOiW3QNyiZr30geGfh0N2FgS96OWALAyje+OmXQj8INFPCIrZRNpX4V3rKpETF1S+3bmmHsVRN+/SzMKgK8AQywtOQHk6sGaKbdd1m63Qq2unLAx715+wPuLgySjpH/qfyXxb2AJV+IiviHP1pNDAGSO2QJr39nsPlYWii+0h/2HYr8AnpnBVUDC0g2nFDkRoMzIljcWrOzG0SeCnWYy9f49V51ZbGFpFtsZHlwlwhUhw3ka2elNE0aNI50MWljcxoEEZ/I8dVlgJEz3xz1C8hcsl0081o4cb1Y2y7I5PXkx7KGwqZTkAq7GV3KMDHHI7mZOivzFm4lx3KEVVegfcEBs+hu7Vjfes=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
