travis:
  secure:
    BINSTAR_TOKEN: eRgknU9Tnni8N86vj6UfrMlLbz+FPtFrh36s2ZSEcFv31pbHr/gcAlYOqXLOpVkv0HTMerxlvCvUCXtEsJ1kVHB6mZBmH+/YY2D9dzOrSE37qKcMZssjGpC62rNL59lay/SS7Ek3yyDxm8AToLiZLP5eDAUzQgVNBYD/XrbpipaIhtu7nTv8EmQA9o0WiN0ZSque41WhnZ0FehYiHlMM/hX/klJKs7nwV8WFAnaQzqIG0SkpNdDyU+FYviKNzdZEgrbUcgMb9A/fWUqWbnI5hLZu/gKHoB6TRJT43F9mD2MRPW1bcHze25lFtmfSW0sI7nSGjwrjIlmsScn8GklUvZKJlm8rZN/9usGIrT3jBv0dIgMHWYYkClw1e6Kb/quVDlMZ8E2gdbyf8sMuc46eVMjjbUZUeu5mxQAmBkwAKyvaSt0RwLWAfvMAbC9u+kR45fPOwMxMWs+Y/fCWRYJHx/nFkKSWzT7eKQ4y03w81ZjnFipg2QK5hors1AaM4lJZTnSa7rHayw0oOSag3ZB666fNovno5nF54oLE5WKq7AmZ2O23lWYtOeYVFEbVG5ZV7J6n40zN2gXp5HemnQJ9Oypf81nXfLeTtoaQIRthiZzHwYnBcPNOLvxg6Sb/yrUDOnLlBmm9fyjJzl7pLlaEoXn++6qfSFD1cx0Y9N35Rm8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
